radar_pcl_filter_node:
  ros__parameters:
    drone_threshold: 1.0
    leaf_size: 0.35
    cluster_crop_radius: 10.0
    ground_threshold: -1.0
    line_model_inlier_threshold: 10.0
    radar_elevation_fov: 40.0
    radar_azimuth_fov: 120.0
    line_or_point_follow: "point"
    
offboard_control:
  ros__parameters:
    powerline_following_distance: 5.0
    powerline_following_speed: 3.5
